#!/usr/bin/env bash

# Dependencies: see ./util/crosscompile

set -ue

DIST_DIR=$1

./util/crosscompile \
    -t "armv7-unknown-linux-gnueabihf" \
    -n "ipdisserver" \
    -n "ipdisscan" \
    -d "${DIST_DIR}"
